"use client";

import { useCallback, useEffect, useMemo, useState } from "react";
import { ArrowDownRight, ArrowUpRight, CalendarDays, ChevronLeft, ChevronRight, CreditCard, Landmark, Moon, Pencil, Plus, ReceiptText, Sun, Trash2, WalletCards, X } from "lucide-react";

type Tx = { id:number; description:string; category:string; account:string; type:"income"|"expense"; recurrence:"one_time"|"monthly"|"installment"; amountCents:number; startDate:string; installmentCount:number };
type Form = Omit<Tx,"id"> & { id?:number; value:string };
const accounts = ["Conta Principal", "Conta Secundária"];
const categories = ["Moradia","Alimentação","Transporte","Saúde","Educação","Lazer","Assinaturas","Salário","Outros"];
const now = new Date();
const initial:Form = { description:"",category:"Moradia",account:accounts[0],type:"expense",recurrence:"one_time",amountCents:0,value:"",startDate:new Date().toISOString().slice(0,10),installmentCount:2 };
const brl = (c:number) => new Intl.NumberFormat("pt-BR",{style:"currency",currency:"BRL"}).format(c/100);
const monthKey = (d:Date) => `${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,"0")}`;
const plusMonths = (base:Date,n:number) => new Date(base.getFullYear(),base.getMonth()+n,1);
const monthDiff = (a:string,b:string) => { const [ay,am]=a.split("-").map(Number),[by,bm]=b.split("-").map(Number); return (by-ay)*12+bm-am; };
const applies = (t:Tx,key:string) => { const start=t.startDate.slice(0,7), diff=monthDiff(start,key); return diff>=0 && (t.recurrence==="monthly" || (t.recurrence==="installment" && diff<t.installmentCount) || (t.recurrence==="one_time" && diff===0)); };

export default function Home(){
  const [items,setItems]=useState<Tx[]>([]),[month,setMonth]=useState(new Date(now.getFullYear(),now.getMonth(),1));
  const [form,setForm]=useState<Form>(initial),[open,setOpen]=useState(false),[filter,setFilter]=useState<"all"|"income"|"expense">("all"),[busy,setBusy]=useState(true),[message,setMessage]=useState(""),[light,setLight]=useState(false);
  const load=useCallback(async()=>{try{const r=await fetch("/api/transactions"); if(!r.ok) throw new Error(); setItems((await r.json()).transactions)}catch{setMessage("Não foi possível carregar os lançamentos.")}finally{setBusy(false)}},[]);
  useEffect(()=>{void load()},[load]);
  useEffect(()=>{const saved=localStorage.getItem("nx-theme")==="light";setLight(saved);document.documentElement.classList.toggle("light",saved)},[]);
  const toggleTheme=()=>setLight(v=>{const next=!v;document.documentElement.classList.toggle("light",next);localStorage.setItem("nx-theme",next?"light":"dark");return next});
  const key=monthKey(month), visible=useMemo(()=>items.filter(t=>applies(t,key)),[items,key]);
  const income=visible.filter(t=>t.type==="income").reduce((s,t)=>s+t.amountCents,0), expense=visible.filter(t=>t.type==="expense").reduce((s,t)=>s+t.amountCents,0), balance=income-expense;
  const accountTotals=accounts.map(account=>{const list=visible.filter(t=>t.account===account);return {account,income:list.filter(t=>t.type==="income").reduce((s,t)=>s+t.amountCents,0),expense:list.filter(t=>t.type==="expense").reduce((s,t)=>s+t.amountCents,0)}});
  const rows=visible.filter(t=>filter==="all"||t.type===filter).sort((a,b)=>b.startDate.localeCompare(a.startDate));
  const startNew=(type:"income"|"expense")=>{setForm({...initial,type});setOpen(true)};
  const edit=(t:Tx)=>{setForm({...t,value:(t.amountCents/100).toFixed(2).replace(".",",")});setOpen(true)};
  const save=async(e:React.FormEvent)=>{e.preventDefault();const value=Number(form.value.replace(/\./g,"").replace(",","."));if(!form.description.trim()||!value){setMessage("Informe uma descrição e um valor.");return}setBusy(true);const payload={...form,amountCents:Math.round(value*100)};try{const r=await fetch("/api/transactions",{method:form.id?"PUT":"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(payload)});if(!r.ok)throw new Error();await load();setOpen(false);setMessage("Lançamento salvo com sucesso.")}catch{setMessage("Não foi possível salvar. Tente novamente.")}finally{setBusy(false)}};
  const remove=async(id:number)=>{if(!confirm("Excluir este lançamento?"))return;await fetch(`/api/transactions?id=${id}`,{method:"DELETE"});setItems(x=>x.filter(t=>t.id!==id));setMessage("Lançamento excluído.")};
  useEffect(()=>{const ctx=(document as Document & {modelContext?:{registerTool:(x:unknown,o?:unknown)=>unknown}}).modelContext;if(!ctx?.registerTool)return;const c=new AbortController();try{ctx.registerTool({name:"list_month_summary",title:"Consultar resumo mensal",description:"Retorna receitas, despesas e saldo do mês atualmente exibido.",inputSchema:{type:"object",properties:{},additionalProperties:false},annotations:{readOnlyHint:true},execute:()=>({month:key,income:brl(income),expense:brl(expense),balance:brl(balance)})},{signal:c.signal})}catch{}return()=>c.abort()},[key,income,expense,balance]);
  return <main className="app-shell">
    <aside className="sidebar"><div className="brand"><div className="logo">NX</div><div><b>Borges Franco</b><span>Finanças da família</span></div></div><nav><button className="active"><WalletCards/>Visão mensal</button><button onClick={()=>startNew("income")}><ArrowUpRight/>Nova receita</button><button onClick={()=>startNew("expense")}><ArrowDownRight/>Nova despesa</button></nav><div className="side-note"><Landmark/><div><small>Controle seguro</small><b>Dados salvos na nuvem</b></div></div></aside>
    <section className="workspace"><header><div><span className="eyebrow">FINANÇAS FAMÍLIA BORGES FRANCO</span><h1>Visão financeira</h1></div><div className="header-tools"><button className="theme-toggle" onClick={toggleTheme} aria-label="Alternar tema">{light?<Moon/>:<Sun/>}</button><div className="month-control"><button aria-label="Mês anterior" onClick={()=>setMonth(plusMonths(month,-1))}><ChevronLeft/></button><div><CalendarDays/><span>{month.toLocaleDateString("pt-BR",{month:"long",year:"numeric"})}</span></div><button aria-label="Próximo mês" onClick={()=>setMonth(plusMonths(month,1))}><ChevronRight/></button></div></div></header>
      {message&&<button className="toast" onClick={()=>setMessage("")}>{message}<X/></button>}
      <div className="hero"><div><span>Saldo previsto do mês</span><strong className={balance<0?"negative":""}>{brl(balance)}</strong><p>{income?`${Math.round(expense/income*100)}% da receita já está comprometida` : "Cadastre suas receitas para acompanhar o saldo"}</p></div><div className="hero-actions"><button className="btn light" onClick={()=>startNew("income")}><Plus/>Receita</button><button className="btn lime" onClick={()=>startNew("expense")}><Plus/>Despesa</button></div></div>
      <div className="summary-grid"><article className="metric"><div className="metric-icon green"><ArrowUpRight/></div><div><span>Receitas</span><strong>{brl(income)}</strong><small>Entradas do mês</small></div></article><article className="metric"><div className="metric-icon red"><ArrowDownRight/></div><div><span>Despesas</span><strong>{brl(expense)}</strong><small>Fixas, parcelas e avulsas</small></div></article><article className="metric"><div className="metric-icon blue"><ReceiptText/></div><div><span>Contas do mês</span><strong>{visible.filter(t=>t.type==="expense").length}</strong><small>{visible.filter(t=>t.recurrence==="monthly").length} lançamentos mensais</small></div></article></div>
      <div className="accounts"><div className="section-title"><div><span className="eyebrow">SUAS CONTAS</span><h2>Valores por conta</h2></div></div><div className="account-grid">{accountTotals.map((a,i)=><article className={`account-card a${i}`} key={a.account}><div><CreditCard/><span>{a.account}</span></div><strong>{brl(a.income-a.expense)}</strong><footer><span>Entradas <b>{brl(a.income)}</b></span><span>Saídas <b>{brl(a.expense)}</b></span></footer></article>)}</div></div>
      <section className="ledger"><div className="section-title"><div><span className="eyebrow">MOVIMENTAÇÕES</span><h2>Lançamentos do mês</h2></div><div className="filters">{[["all","Todos"],["income","Receitas"],["expense","Despesas"]].map(([v,l])=><button key={v} className={filter===v?"on":""} onClick={()=>setFilter(v as typeof filter)}>{l}</button>)}</div></div>
        <div className="table-wrap">{busy&&!items.length?<div className="empty">Carregando seus dados…</div>:!rows.length?<div className="empty"><ReceiptText/><b>Nenhum lançamento neste mês</b><span>Adicione uma receita ou despesa para começar.</span></div>:<table><thead><tr><th>Descrição</th><th>Tipo</th><th>Conta</th><th>Valor</th><th></th></tr></thead><tbody>{rows.map(t=>{const n=monthDiff(t.startDate.slice(0,7),key)+1;return <tr key={t.id}><td><b>{t.description}</b><span>{t.category} · {new Date(t.startDate+"T12:00:00").toLocaleDateString("pt-BR")}</span></td><td><em className={t.recurrence}>{t.recurrence==="monthly"?"Fixo mensal":t.recurrence==="installment"?`Parcela ${n}/${t.installmentCount}`:"Gasto do mês"}</em></td><td>{t.account}</td><td className={t.type}>{t.type==="expense"?"− ":"+ "}{brl(t.amountCents)}</td><td><button className="icon-btn" onClick={()=>edit(t)} aria-label="Editar"><Pencil/></button><button className="icon-btn danger" onClick={()=>remove(t.id)} aria-label="Excluir"><Trash2/></button></td></tr>})}</tbody></table>}</div>
      </section>
    </section>
    {open&&<div className="overlay" onMouseDown={e=>{if(e.target===e.currentTarget)setOpen(false)}}><form className="entry-card" onSubmit={save}><div className="entry-head"><div><span className="eyebrow">{form.id?"EDITAR":"NOVO LANÇAMENTO"}</span><h2>{form.type==="income"?"Adicionar receita":"Adicionar despesa"}</h2></div><button type="button" className="icon-btn" onClick={()=>setOpen(false)}><X/></button></div><div className="type-switch"><button type="button" className={form.type==="income"?"selected income-bg":""} onClick={()=>setForm(f=>({...f,type:"income",recurrence:f.recurrence==="installment"?"one_time":f.recurrence}))}>Receita</button><button type="button" className={form.type==="expense"?"selected expense-bg":""} onClick={()=>setForm(f=>({...f,type:"expense"}))}>Despesa</button></div><div className="form-grid"><label className="wide">Descrição<input required value={form.description} onChange={e=>setForm(f=>({...f,description:e.target.value}))} placeholder="Ex.: Aluguel, salário, supermercado"/></label><label>Valor<input required inputMode="decimal" value={form.value} onChange={e=>setForm(f=>({...f,value:e.target.value}))} placeholder="0,00"/></label><label>Data inicial<input type="date" required value={form.startDate} onChange={e=>setForm(f=>({...f,startDate:e.target.value}))}/></label><label>Conta<select value={form.account} onChange={e=>setForm(f=>({...f,account:e.target.value}))}>{accounts.map(x=><option key={x}>{x}</option>)}</select></label><label>Categoria<select value={form.category} onChange={e=>setForm(f=>({...f,category:e.target.value}))}>{categories.map(x=><option key={x}>{x}</option>)}</select></label><label className="wide">Como lançar?<select value={form.recurrence} onChange={e=>setForm(f=>({...f,recurrence:e.target.value as Form["recurrence"]}))}><option value="one_time">Somente neste mês</option><option value="monthly">Mensal fixo</option>{form.type==="expense"&&<option value="installment">Compra parcelada</option>}</select></label>{form.recurrence==="installment"&&<label className="wide">Quantidade de parcelas<input type="number" min="2" max="120" value={form.installmentCount} onChange={e=>setForm(f=>({...f,installmentCount:Number(e.target.value)}))}/></label>}</div><div className="form-actions"><button type="button" className="btn ghost" onClick={()=>setOpen(false)}>Cancelar</button><button className="btn lime" disabled={busy}>{busy?"Salvando…":"Salvar lançamento"}</button></div></form></div>}
  </main>
}
